sudo: required	

services:
- docker

language: node_js

cache:
  directories:
  - $HOME/google-cloud-sdk/

env:
# To deploy, define below vars in this .travis.yml file or in Travi-CI configuration
#- TRAVIS_CI_DEPLOYMENT=https://github.com/smartprocure/einstein-nanobots/tree/master/dev-ops/travis-ci
- TRAVIS_CI_DEPLOYMENT=https://github.com/smartprocure/einstein-nanobots/tree/ZD19127/dev-ops/travis-ci
  VERSION_MAJOR=${VERSION_MAJOR:=undefined}
  VERSION_MINOR=${VERSION_MINOR:=undefined}
  BUILD_VERSION_FILE_DIR="./client/public"
  BUILD_VERSION_FILE="build_version.txt"

before_install:
# 

install:
#

script:
#
#- docker build    -t    ${IMAGE} . || exit 1

after_success:
# 
- curl ${TRAVIS_CI_DEPLOYMENT}/deploy.sh | /bin/bash -x
