sudo: required	

services:
- docker

language: node_js

cache:
  directories:
  - $HOME/google-cloud-sdk/

env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1 GCLOUD_PROJECT_NAME=silent-presence-117620
  CLOUDSDK_CORE_PROJECT=silent-presence-117620 CONTAINER_CLUSTER=dom-example-cluster CLOUDSDK_COMPUTE_ZONE=us-central1-b 
  GCLOUD_EMAIL=continuous-integration-test-tr@silent-presence-117620.iam.gserviceaccount.com
  GOOGLE_APPLICATION_CREDENTIALS=client-secret.json

 #hello-world-deployment

before_install:
#- env
- cd containerengine/hello-world
- openssl aes-256-cbc -K $encrypted_0fc78259f5c7_key -iv $encrypted_0fc78259f5c7_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud --version
- gcloud config list
- gcloud config set disable_usage_reporting true

install:
- gcloud --quiet components update kubectl
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account $GCLOUD_EMAIL --key-file $GOOGLE_APPLICATION_CREDENTIALS
- gcloud config set project $GCLOUD_PROJECT_NAME
- gcloud config set compute/zone $CLOUDSDK_COMPUTE_ZONE

script:
- docker build    -t gcr.io/$GCLOUD_PROJECT_NAME/hw:v${TRAVIS_JOB_NUMBER} .
- gcloud docker -- push gcr.io/$GCLOUD_PROJECT_NAME/hw:v${TRAVIS_JOB_NUMBER} > /dev/null
- gcloud container clusters get-credentials $CONTAINER_CLUSTER --zone $CLOUDSDK_COMPUTE_ZONE
- kubectl rolling-update hello-world-deployment --image=gcr.io/silent-presence-117620/hw:v${TRAVIS_JOB_NUMBER}
#- kubectl set image deployment/hello-world-deployment hello-world=gcr.io/$GCLOUD_PROJECT_NAME/hw:v${TRAVIS_JOB_NUMBER}

after_success:
- cal
