sudo: required	

services:
- docker

language: node_js

env:
#
# To deploy, define below vars in this .travis.yml file or in Travi-CI configuration
#

- TRAVIS_CI_DEPLOYMENT=https://raw.githubusercontent.com/smartprocure/einstein-nanobots/ZD19127/dev-ops/travis-ci

  VERSION_MAJOR=${VERSION_MAJOR:=undefined}
  VERSION_MINOR=${VERSION_MINOR:=undefined}

  BUILD_VERSION_FILE_DIR="./client/public"
  BUILD_VERSION_FILE="build_version.txt"

before_install:
#
- curl ${TRAVIS_CI_DEPLOYMENT}/deploy.sh?token=ATsdVTGItj920Iu1ZMHuQHqbmKtmW779ks5YveUlwA%3D%3D | /bin/bash -x -v

install:
#
- echo "Nothing to do during install" 

script:
#
- echo "Nothing to do after install" 

after_success:
# 
- echo "Horray !!! We have reached the end !!!" 
