sudo: false
language: node_js
node_js:
- '4'
cache:
  directories:
  - $HOME/google-cloud-sdk/
env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1 GCLOUD_PROJECT_NAME=silent-presence-117620
  CLOUDSDK_CORE_PROJECT=hello-world
before_install:
- openssl aes-256-cbc -K $encrypted_0fc78259f5c7_key -iv $encrypted_0fc78259f5c7_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- gcloud --version
after_success:
- gcloud --quiet components update kubectl
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- cd containerengine/hello-world
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project $GCLOUD_PROJECT_NAME
- ssh-keygen -f ~/.ssh/google_compute_engine -N ""
- docker build    -t gcr.io/$GCLOUD_PROJECT_NAME/hw:v${TRAVIS_JOB_NUMBER} .
- gcloud docker push gcr.io/$GCLOUD_PROJECT_NAME/hw:v${TRAVIS_JOB_NUMBER} > /dev/null
- gcloud container clusters get-credentials $CLOUDSDK_CORE_PROJECT
- kubectl set image deployment/hello-world-deployment hello-world=gcr.io/GCLOUD_PROJECT_NAME/hw:v${TRAVIS_JOB_NUMBER}
